### ISSUE TITLE
npm test broken because of recent changes

### ISSUE THREAD

**Issue by glathoud** [glathoud/transfun#11]
(probably because of #7 )

```
npm test
...
  0 passing (87ms)
  1 failing

  1) all
       should return true, and not throw any error:
     SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
      at Function (native)
      at ensure_appimpl (transfun.js:987:37)
      at Function.transfun [as map] (transfun.js:891:21)
      at test (test.js:556:61)
 ```

**Comment by glathoud** [comment]
okay I'll just put "use strict" at the top of the body of each generated function, won't hurt anyway

**Comment by glathoud** [comment]
"use strict" could improve the performance in some cases as well
